# fly.toml app configuration file generated for lialili on 2023-08-15T14:02:17+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lialili"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.0"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_HOST="lialilishopdb.internal"
  DB_PORT="3306"
  DB_DATABASE="lialilidb"
  DB_USERNAME="lialili"
  DB_PASSWORD="lialili123"

  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
